server {
    listen 80;
    server_name taskflow-nont.centralindia.cloudapp.azure.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name taskflow-nont.centralindia.cloudapp.azure.com;

    ssl_certificate /etc/letsencrypt/live/taskflow-nont.centralindia.cloudapp.azure.com/fullchain.pem
    ssl_certificate_key /etc/letsencrypt/live/taskflow-nont.centralindia.cloudapp.azure.com/privkey.pem

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://server:3231;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}